import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle, 
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
import Image from "next/image";
import lao from "../public/lao-tech.jpg";
import tpl from "../public/tpl-log.jpg";
import ed from "../public/ed-app.jpg";
import weather from "../public/weather.jpg";
import inventory from "../public/inventory.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luis Olivero Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl text-gray-700">LAO Technologies</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-gray-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-700 font-medium">
              Luis Olivero
            </h2>
            <h3 className="text-2xl py-2">React Application Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Creating software applications for everyday problems, no matter the field! 3PL Logistics, Educational, Local Weather, Inventory Apps to take organizations to their fullest potential! 
            </p>
          </div>
          {/* Replace Twitter for Github, Linkedin good, Replace Youtube for Email */}
          <div className="text-5xl flex justify-center gap-16 pt-3 pb-12 text-cyan-600">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillMail />
          </div>
          {/* Change image to square of 4 to represent fields listed above */}
          {/* <div className="relative mx-auto w-80 h-80">
            <Image src={lao} layout="fill" objectFit="cover" />
          </div> */}
          <div className="columns-2 mx-auto pb-12 w-50 h-50">
            <Image src={ed} objectFit="cover"/>
            <Image src={tpl} />
            <Image src={weather} />
            <Image src={inventory} />
          </div>
        </section>
        
        <section>
          <div className="bg-gradient-to-b from-gray-500 to-cyan-500 text-white text-center min-h-screen">
            <h3 className="text-5xl py-3">Future Projects</h3>
          </div>

        </section>
      </main>
    </div>
  );
}
